### ISSUE TITLE
Investigate adding a build/test rule that determines if all Bazel packages have a bzlformat_pkg

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_bzlformat#5]
## Description

If one is using `rules_bzlformat` to enforce code formatting standards, it would be ideal to also determine if all Bazel packages are covered by the rule. Solutions like pre-commit hooks handle this because they work outside the build looking for all of the files that match a pattern.

## Excerpt from Slack Thread

https://bazelbuild.slack.com/archives/CA31HN1T3/p1635972050227400?thread_ts=1635888823.198100&cid=CA31HN1T3

Marc Plano-Lesay  1 day ago
Do you have a solution for not forgetting the bzlformat_pkg in a new BUILD file? It's been my main blocker in implementing something like this in the past - all the other source files I have are by nature used in other targets and I can hook into that, but forgetting that macro in a new BUILD file seems really easy to do

Marc Plano-Lesay  19 hours ago
@Chuck Grindel that would help with packages containing macro and/or rule definitions (in which case we're likely to have a bzl_library target indeed), but wouldn't help with good old BUILD files, would it?

**Comment by cgrindel** [comment]
This appears to be working. I will generate release 0.3.0 shortly to include this functionality.

**Comment by Kernald** [comment]
Following up on this, from the README:

```
# Add this to your CI test runs.
$ bazel run //:bzlformat_missing_pkgs_test
```

Is there any reason why this isn't (or maybe it is, but using `run` in the README seems off) a test target? This would allow to just run `bazel test //...` and forget about that entirely.

**Comment by cgrindel** [comment]
@Kernald The utility does a couple of `bazel query` calls from the `BUILD_WORKSPACE_DIRECTORY` directory. Unfortunately, tests do not provide that variable. So, the best that I could come up with was to provide it as an executable target.
